version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8080
        - LOG_LEVEL=DEBUG
        - MONGO_URI=mongodb+srv://challengeUser:WUMglwNBaydH8Yvu@challenge-xzwqd.mongodb.net/getir-case-study?retryWrites=true
        - MONGO_DB=getir-case-study
        - MONGO_COLLECTION=records
        - REDIS_URL=redis://redis_local:6379
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - redis
    command: ["/usr/local/bin/waitforit", "-address=redis://redis_local:6379", "-timeout=20", "--", "/app"]

  redis:
    image: redis:alpine
    container_name: redis_local
    restart: unless-stopped
    ports:
      - 6379:6379
